### ISSUE TITLE
Question about the SMICA DX12 Planck18 param file

### ISSUE THREAD

**Issue by fbianchini** [carronj/plancklens#13]
Hi Julien,

I have a simple question about the parameter file for lensing reconstruction on the Planck public release 3 SMICA CMB map.

What is the content of the `dcl ` and `dcl _dat` files, I thought they were like theory/data CMB power spectra but they don't really look like that, maybe I'm missing something!

Cheers,
~federico

**Comment by carronj** [comment]
Hi Federico,

There is visible power mismatch between the Planck dx12 SMICA sims and data maps (in TT mostly, up to maybe 5% at the highest CMB ells relevant there).  The dcls are some estimate of this power which is then used to generate some additional Gaussian power to improve the sim of data power spectra consistency. 

Best,

Julien

**Comment by fbianchini** [comment]
Thanks for the explanation, that makes sense, apologies if this was mentioned somewhere in the doco and I missed it!

Cheers,
~federico
